version: "3"
services:
  app:
    build: 
      context: .
      args:
        - host=0.0.0.0
        - port=8000
    ports:
      - "8000:8000"
    volumes:
    - ./app:/app:ro
    - ./db:/db:rw
    environment:
      - DATABASE_URI=sqlite:////db/database.db
    