version: "3"
services:
  app:
    build: 
      context: .
      args:
        - host=0.0.0.0
        - port=8000
    ports:
      - "8000:8000"
    volumes:
    - ./db:/app/db/:rw
    - ./database.py:/app/database.py:ro
    - ./models.py:/app/models.py:ro
    - ./app.py:/app/app.py:ro
    
